381807-1
AMyachev/labs-c-plus-plus pull request #6
Opened 2019-12-19 20:36 UTC by DenisParal

Этот парень из первой группы, который хотел отправить лабу. Параничев Денис вариант 10, двусвязный список.

2019-12-19 23:17 UTC, AMyachev commented
@DenisParal выпили pch, если не используешь, и я не могу просматривать LinkedList.cpp - надо поправить это, похожая проблема была у @SKholkin

2019-12-19 23:18 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		list() {
Зачем определять пустой конструктор?

2019-12-19 23:29 UTC, AMyachev requested changes

2019-12-19 23:29 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* pointer;
Зачем нужно хранить этот указатель?

2019-12-19 23:29 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
функции не зависящие от шаблонного параметра имеет смысл выносить в отдельный .cpp

2019-12-19 23:29 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
нет проверки индекса для проверки выхода за границы

2019-12-20 08:39 UTC, AMyachev requested changes

2019-12-20 08:39 UTC, AMyachev commented on LinkedList/LinkedList.h
> +			first_element->left = last_element;
здесь с точностью до названия всё, что делается в методе push. Вынеси это в отдельную функцию (тебе по сути надо знать для новой ноды что слева, что справа и значение для неё)

2019-12-20 08:39 UTC, AMyachev commented on LinkedList/LinkedList.h
> +			first_element->left = last_element;
и в принципе эту отдельную функцию можно будет использовать в методе insert

2019-12-22 16:38 UTC, denis-paranichev reviewed
Все конечные изменения находятся в последнем коммите, версия 3

2019-12-22 16:38 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		list() {
Исправил в новой версии, визуалка выдавала ошибку, мол функцию он не видел какую-то (видимо, конструктор без параметров)

2019-12-22 16:38 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	list* pointer;
В новой версии не храню, изменил пару функций

2019-12-22 16:38 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
Смысл в этом, конечно, есть, но в функциях класса везде используется переменная value шаблонного параметра, не увидел смысла в введении проверки на выход за границы, т.к. лист цикличный, данная функция реализована таким образом, что ошибки не будет при вводе чисел, выходящих за размер листа. Можно вводить даже отрицательные числа, в этом случае отсчет просто пойдет с конца к началу.

2019-12-22 16:38 UTC, DenisParal commented on LinkedList/LinkedList.h
> +			first_element->left = last_element;
Сделал в версии 3

2019-12-22 19:43 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* get_elem(int index, list* pointer) {
это рекурсивный вариант, который проходит в худшем случае все элементы.
как мы знаем - глубина рекурсии ограничена.
**попробуй** на списке 10^6 интовых элементов найти последний.

2019-12-22 19:59 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	list* get_elem(int index, list* pointer) {
Понял, изменил

2019-12-22 20:09 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
Когда здесь будет core dump?

2019-12-22 20:49 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
Когда в листе не будет элементов, в последней версии функция вернет nullptr, исправил так же LinkedList.cpp.

2019-12-22 20:52 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
Я не понимаю, почему файл LinkedList.cpp отмечается как бинарный, я добавил файл .gitattributes, даже так он считает его бинарным.

2019-12-22 21:02 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
давай пойдём не по пути `.gitattributes`

- открой файл LinkedList.h и посмотри какая кодировка у него

- потом открой LinkedList.cpp и сохрани его в той же кодировке как и у хедера

2019-12-22 21:03 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
и также удали остальные бинарные файлы

2019-12-22 21:07 UTC, AMyachev requested changes

2019-12-22 21:07 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	void insert(int pos, T* value) {
в этой функции memory leak

2019-12-22 21:12 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	void insert(int pos, T* value) {
Да, не заметил, забыл удалить строчку, исправлю в новом коммите. А что делать с .cpp, я так и не понял, я изменил кодировку, но он до сих пор считается бинарным файлом. Я прочитал, что иногда не хватает кодировки для определения типа.

2019-12-22 21:13 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
какая кодировка у этого файла? должна быть UTF-8

2019-12-22 21:14 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
UTF-8 и есть, как и у хедера

2019-12-22 21:16 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
ты его просто изменил, или удалил и заново добавил?

2019-12-22 21:22 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
Просто изменил

2019-12-22 21:29 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
попробуй второй вариант

2019-12-22 21:46 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		return(get_elem(index, startElement)->value);
Сделал

2019-12-22 21:51 UTC, AMyachev commented
удали все файлы из папки `.vs`

2019-12-22 22:11 UTC, DenisParal commented
Удалил все файлы из папки .vs

2019-12-22 22:15 UTC, AMyachev commented
Напиши все требования к твоей задаче, а то у тебя сверху вообще двусвязный список написан.

2019-12-22 22:51 UTC, DenisParal commented
Сделал описание задачи

2019-12-22 22:58 UTC, AMyachev commented
Не надо менять моё readme). Сделай readme в своей папке

2019-12-22 23:00 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
Почему ты сделал цикличный, если в задании просто двусвязный список?

2019-12-22 23:02 UTC, DenisParal commented
Сделал )

2019-12-23 13:45 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
В задании сказано двусвязный циклический список

2019-12-23 15:08 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	list* get_elem(int index) {
а в readme нет

2019-12-23 15:13 UTC, AMyachev commented
Я бы хотел видеть следующее (для начала):

- конструктор копирования
- оператор присваивания
- возможность удалить объект по условию(условие определяется функцией предикатом). Можешь посмотреть здесь: https://en.cppreference.com/w/cpp/container/list/remove

2019-12-23 18:34 UTC, DenisParal commented
Сделал задание

2019-12-23 19:56 UTC, AMyachev requested changes

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.cpp
> +		/*user_list->erase_if([](person* p) {return p->getName() == "Denis"; });
забыл удалить

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		temp->value = nullptr;
почему так?

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		list* pointer = copylist.startElement;
startElement же приватное поле. Как ты можешь к нему обращаться?

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	LinkedList(LinkedList& copylist):LinkedList() {
почему не const?

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	LinkedList& operator =(LinkedList& copylist) {
const?

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +		if (copylist.size >= this->size) {
зачем обращаться к приватным полям?

2019-12-23 19:56 UTC, AMyachev commented on LinkedList/LinkedList.h
> +	void erase_if(pred f) {
не используется предикат f

2019-12-23 20:07 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		list* pointer = copylist.startElement;
Поле приватное, но я обращаюсь к нему из кода этого класса, поэтому все легально.

2019-12-23 20:25 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		temp->value = nullptr;
Это ложный страх, я на секунду подумал, что delete очистит и сам объект, который хранился под указателем, но нет, я исправил в новой версии.

2019-12-23 20:27 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	LinkedList(LinkedList& copylist):LinkedList() {
Совсем забыл про это, я и так не изменял аргумент, но перестраховаться стоит, изменил в последней версии.

2019-12-23 20:36 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	LinkedList& operator =(LinkedList& copylist) {
Исправил в последнем коммите

2019-12-23 20:41 UTC, DenisParal commented on LinkedList/LinkedList.h
> +		if (copylist.size >= this->size) {
Я посчитал, что работа с указателями напрямую, а не через оператор [] ускорит работу функции, к тому же в последней версии кода аргумент обладает модификатором const, поэтому его нельзя изменить. Единственное, что я не предусмотрел - это запись по приватному адресу.

2019-12-23 20:42 UTC, DenisParal commented on LinkedList/LinkedList.h
> +	void erase_if(pred f) {
Дело в имени аргумента?

2023-10-26 16:41 UTC, closed without merging